// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snacks.Data;

namespace Snacks.Data.Migrations
{
    [DbContext(typeof(SnacksContext))]
    [Migration("20210618092507_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Snacks.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A scrumptious almond cake encrusted with sliced almonds",
                            ImageName = "Almond_Cake.jpg",
                            Name = "Almond Cake",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A delicious curry of potato and cauliflower with Indian spices",
                            ImageName = "Alu-Gobhi_Curry.jpg",
                            Name = "Alu Gobhi Curry",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Delectable savoury cutlet made from fish",
                            ImageName = "Fish_Cutlet.jpg",
                            Name = "Fish Cutlet",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chickpeas made into delicious snack with lamb mutton",
                            ImageName = "Mutton_Chholay.jpg",
                            Name = "Mutton Chholay",
                            Price = 1.49m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A delectable fresh cheese dumpling embedded in Sugar Syrup",
                            ImageName = "Rasgulla.jpg",
                            Name = "Bengali Rasgulla",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fried Besan Coated Lentil Fritters",
                            ImageName = "Sambhar_Vada.jpg",
                            Name = "Sambhar Vada",
                            Price = 8.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
